name: CI Workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  LM_JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          java-package: jdk
      

      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip -Dpmd.skip clean package
        env:
          MAVEN_OPTS: "-Duser.home=$GITHUB_WORKSPACE"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/

      - name: Build Docker image
        run: |
          docker build -t conformance-suite .

      - name: Upload image
        run: |
          docker push brankom77/conformance-suite:tagname