name: CI Workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  LM_JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip -Dpmd.skip clean package
        env:
          MAVEN_OPTS: "-Duser.home=$GITHUB_WORKSPACE"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t conformance-suite .

      - name: Upload image
        run: |
          docker push conformance-suite