name: CI Workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  LM_JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          java-package: jdk
      

      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip -Dpmd.skip clean package
        env:
          MAVEN_OPTS: "-Duser.home=$GITHUB_WORKSPACE"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
  
      - name: Build Docker image
        run: |
          docker build -t brankom77/conformance-suite:${{ github.sha }} -t brankom77/conformance-suite:latest .
  
      - name: List Docker images
        run: |
          docker images
  
      - name: Push Docker image
        run: |
          docker push brankom77/conformance-suite:${{ github.sha }}
          docker push brankom77/conformance-suite:latest